Code/Server/Django_Web_REST_Server/BA01/urls.py
from django.contrib import admin
from django.urls import path, include

# TODO remove unnecessary login / out urls
urlpatterns = [
    path('', include('config.urls')),
    path('rest/', include('rest.urls')),
    path('admin/', admin.site.urls),

]

Code/Server/Django_Web_REST_Server/config/urls.py
from django.urls import path, include

from config import basic_views, app_views

app_name = 'config'
urlpatterns = [
    path('', basic_views.home_store_view, name='home_store_view'),
    path('', include('django.contrib.auth.urls')),
    path('uninstall/<int:id>/', basic_views.uninstall_app, name='uninstall'),
    path('install_app', basic_views.install_app, name='install_app'),

    path('app/<int:id>/', app_views.app_view, name='app_view'),

    # IPTABLES
    path('Firewall-iptables', app_views.iptables_view, name='Firewall-iptables'),
    path('new_iptables_config', app_views.new_iptables_config, name='new_iptables_config'),
    path('delete_iptables_config', app_views.delete_iptables_config, name='delete_iptables_config'),

    # DNS-Firewall
    # path('block_domain', app_views.block_domain, name='block_domain'),
    # path('unblock_domain', app_views.unblock_domain, name='unblock_domain'),

]

Code/Server/Django_Web_REST_Server/rest/urls.py
from django.urls import include, path
from rest_framework import routers

from rest import views
#
# router = routers.DefaultRouter()
# router.register(r'devices', views.DeviceViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('iptables-conf/<int:pk>/', views.IPTablesDeviceDetail.as_view()),
    path('stage1/devices/<int:pk>/', views.Stage1DeviceDetail.as_view()),
    #browsable api security flaws
    #path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

Code/Server/Django_Web_REST_Server/config/models.py
# Create your models here.

Code/Server/Django_Web_REST_Server/rest/models.py
from django.contrib.auth.models import User
from django.db import models


class IoTApplication(models.Model):
    id = models.fields.IntegerField(primary_key=True, auto_created=True)
    name = models.CharField(max_length=50)
    version = models.IntegerField()

    def __str__(self):
        return str(self.name)


class Device(models.Model):
    uuid = models.IntegerField(primary_key=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    applications = models.ManyToManyField(IoTApplication, blank=True, related_name='App')

    def __str__(self):
        return 'device: ' + str(self.uuid)

#App models-----------------------------------------------------------------------------------------------


class IPRule(models.Model):
    id = models.AutoField(primary_key=True)
    device = models.ForeignKey(Device, on_delete=models.CASCADE, related_name='ip_rule')
    chain = models.CharField(max_length=6)  # INPUT/OUTPUT
    destination_port = models.IntegerField()
    packet_type = models.CharField(max_length=10) #TCP,UDP,..
    action = models.CharField(max_length=15)  # Drop,..

    def __str__(self):
        return self.chain + ' | ' + str(self.device)

    class Meta:
        verbose_name_plural = "IP_Rules"
        ordering = ("id",)

Code/Server/Django_Web_REST_Server/config/forms.py
from django import forms

from rest.models import IPRule


class ConfigForm(forms.ModelForm):
    class Meta:
        model = IPRule
        fields = ('chain', 'destination_port', 'packet_type', 'action')

    def __init__(self, *args, **kwargs):
        super(ConfigForm, self).__init__(*args, **kwargs)
        self.fields['destination_port'].widget.attrs.update({'style': 'background-color: #5e42a6;'})


class DeleteConfigForm(forms.Form):
    id = forms.IntegerField(label='ID')

    def __init__(self, *args, **kwargs):
        super(DeleteConfigForm, self).__init__(*args, **kwargs)
        self.fields['id'].widget.attrs.update({'style': 'background-color: #493382;'})

Code/Server/Django_Web_REST_Server/config/views.py
import config.app_views
import config.basic_views

Code/Server/Django_Web_REST_Server/rest/views.py
from django.http import Http404
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework.views import APIView

from rest import permissions as ownPermissions
from rest.models import Device
from rest.serializers import IPTablesDeviceConfigSerializer, Stage1DeviceSerializer
from rest.signer import sign


class Stage1DeviceDetail(APIView):
    permission_classes = [ownPermissions.IsOwner, permissions.IsAuthenticated]

    def get_object(self, pk):
        try:
            return Device.objects.get(pk=pk)
        except Device.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        device = self.get_object(pk)
        self.check_object_permissions(self.request, device)
        serializer = Stage1DeviceSerializer(device)
        data = serializer.data
        data = sign(data)
        return Response(data)


class IPTablesDeviceDetail(APIView):
    permission_classes = [ownPermissions.IsOwner, permissions.IsAuthenticated]

    def get_object(self, pk):
        try:
            return Device.objects.get(pk=pk)
        except Device.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        device = self.get_object(pk)
        self.check_object_permissions(self.request, device)
        serializer = IPTablesDeviceConfigSerializer(device)
        data = serializer.data
        data = sign(data)
        return Response(data)

# class Stage1DeviceViewSet(viewsets.ModelViewSet):
#     """
#     API endpoint that allows users to be viewed or edited.
#     """
#     queryset = Device.objects.all()
#     serializer_class = IPTablesDeviceConfigSerializer
#     permission_classes = [permissions.IsAuthenticated]

# class DeviceViewSet(viewsets.ModelViewSet):
#     """
#     API endpoint that allows users to be viewed or edited.
#     """
#     queryset = Device.objects.all()
#     serializer_class = IPTablesDeviceConfigSerializer
#     permission_classes = [permissions.IsAuthenticated]

Code/Server/Django_Web_REST_Server/templates/IPRuleTableTeplate.html
{% load render_table from django_tables2 %}
<!doctype html>
<html>
    <head>
        <title>Your active Configuration</title>
    </head>
    <body>
        {% render_table table %}
    </body>
</html>

Code/Server/Django_Web_REST_Server/templates/appstore_index.html
<!DOCTYPE HTML>
<!--
	Hyperspace by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    {% load static %}
    <title>Login IoT Config</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href = {% static 'assets/css/main.css' %} />
    <noscript>
        <link rel="stylesheet" href= {% static 'assets/css/noscript.css' %} />
    </noscript>
</head>
<body class="is-preload">

<section id="sidebar">
    <div class="inner">
        <nav>
            <ul>

                    <li>User: {{ user.get_username }}</li>
                    <li>Installed Apps:</li>
                    {% for app in apps %}
                        <li><a href="{% url 'config:app_view' app.id %}">{{ app.name }}</a></li>
                    {% endfor %}
                    <li><a href="{% url 'config:logout' %}?next={{ request.path }}"><b>Logout</b></a></li>

            </ul>
        </nav>
    </div>
</section>

<!-- Wrapper -->
<div id="wrapper">
    <!-- Intro -->
    <section id="intro" class="wrapper style1 fullscreen fade-up">
        <div class="inner">
            {% load render_table from django_tables2 %}
            {% block content %}
                <h1>Available Apps</h1>
                {% render_table table %}
                </div>
                </section>


                <section id="three" class="wrapper style1-alt fade-up">
                    <div class="inner">
                        <h2>Install an App</h2>
                        <p>Install a new App by typing its id into the textfield.</p>
                        <div class="split style1">
                            <section>
                                <form method="POST"
                                      action={% url 'config:install_app' %} class="post-form">{% csrf_token %}
                                    <div class="fields">
                                        {{ form.as_p }}
                                    </div>
                                    <button type="submit" class="save btn btn-default">Install</button>
                                </form>
                            </section>

                        </div>
                    </div>
                </section>

            {% endblock %}
</div>
</body>
<!-- Footer -->
<footer id="footer" class="wrapper style1">
    <div class="inner">
        <ul class="menu">
            <li>&copy; Leon Lukas. All rights reserved.</li>
        </ul>
    </div>
</footer>

<!-- Scripts -->
{% load static %}
<script src={% static 'assets/js/jquery.min.js' %}></script>
<script src={% static 'assets/js/jquery.scrollex.min.js' %}></script>
<script src={% static 'assets/js/jquery.scrolly.min.js' %}></script>
<script src={% static 'assets/js/browser.min.js' %}></script>
<script src={% static 'assets/js/breakpoints.min.js' %}></script>
<script src={% static 'assets/js/util.js' %}></script>
<script src={% static 'assets/js/main.js' %}></script>

</body>
</html>

Code/Server/Django_Web_REST_Server/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>IoT-Config</title>{% endblock %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
</head>
<style>
.content {
  margin: auto;
}
</style>
<body>



{% block sidebar %}
    <ul class="sidebar-nav">


        {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li><a href="{% url 'config:logout' %}?next={{ request.path }}">Logout</a></li>
        {% else %}
            <li><a href="{% url 'config:login' %}?next={{ request.path }}">Login</a></li>
        {% endif %}
    </ul>{% endblock %}
{% block content %}<!-- default content text (typically empty) -->{% endblock %}
</body>
</html>

Code/Server/Django_Web_REST_Server/templates/dns-fw_index.html
<!DOCTYPE HTML>
<!--
	Hyperspace by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    {% load static %}
    <title>Login IoT Config</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href = {% static 'assets/css/main.css' %} />
    <noscript>
        <link rel="stylesheet" href= {% static 'assets/css/noscript.css' %} />
    </noscript>
</head>
<body class="is-preload">

<section id="sidebar">
    <div class="inner">
        <nav>
            <ul>
                <li>User: {{ user.get_username }}</li>
                <li><a href="{% url 'config:home_store_view' %}?next={{ request.path }}">Home</a></li>
                <li><a href="{% url 'config:logout' %}?next={{ request.path }}">Logout</a></li>
            </ul>
        </nav>
    </div>
</section>

<!-- Wrapper -->
<div id="wrapper">
    <!-- Intro -->
    <section id="intro" class="wrapper style1 fullscreen fade-up">
        <div class="inner">
            {% load render_table from django_tables2 %}
            {% block content %}
                <h2>Available  DNS Domains:</h2>
                    {% render_table not_installed %}
                <h2>Your blocked DNS Domains:</h2>
                    {% render_table installed %}

                </div>
                </section>


                <section id="two" class="wrapper style1-alt fade-up">
                    <div class="inner">
                        <h2>Change your Configuration</h2>
                        <p>Block or unblock domains by typing its id into corresponding the field.</p>
                        <div class="split style1">
                            <section>
                                <form method="POST"
                                      action={% url 'config:block_domain'%} class="post-form">{% csrf_token %}
                                    <div class="fields">
                                        {{ form.as_p }}
                                    </div>
                                    <button type="submit" class="save btn btn-default">Block</button>
                                </form>
                            </section>
                            <section>
                                <form method="POST"
                                      action={% url 'config:unblock_domain'%} class="post-form">{% csrf_token %}
                                    <div class="fields">
                                        {{ form.as_p }}
                                    </div>
                                    <button type="submit" class="save btn btn-default">Unblock</button>
                                </form>
                            </section>

                        </div>
                    </div>
                </section>


                <section id="two" class="wrapper style1 fade-up">
                    <div class="inner">
                        <h2>Uninstall</h2>
                        <p>If you want to uninstall DNS-Firewall click the button</p>
                        <div class="split style1">
                            <section>
                                <form method="POST"
                                    action={% url 'config:uninstall' id %} class="post-form">{% csrf_token %}
                                    <button type="submit" class="save btn btn-default">Uninstall</button>
                                </form>
                            </section>

                        </div>
                    </div>
                </section>

            {% endblock %}
</div>
</body>
<!-- Footer -->
<footer id="footer" class="wrapper style1-alt">
    <div class="inner">
        <ul class="menu">
            <li>&copy; Leon Lukas. All rights reserved.</li>
        </ul>
    </div>
</footer>

<!-- Scripts -->
{% load static %}
<script src={% static 'assets/js/jquery.min.js' %}></script>
<script src={% static 'assets/js/jquery.scrollex.min.js' %}></script>
<script src={% static 'assets/js/jquery.scrolly.min.js' %}></script>
<script src={% static 'assets/js/browser.min.js' %}></script>
<script src={% static 'assets/js/breakpoints.min.js' %}></script>
<script src={% static 'assets/js/util.js' %}></script>
<script src={% static 'assets/js/main.js' %}></script>

</body>
</html>

Code/Server/Django_Web_REST_Server/templates/hyperspace/generic.html
<!DOCTYPE HTML>
<!--
	Hyperspace by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Generic - Hyperspace by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="assets/css/main.css" />
		<noscript><link rel="stylesheet" href="assets/css/noscript.css" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
				<a href="index.html" class="title">Hyperspace</a>
				<nav>
					<ul>
						<li><a href="index.html">Home</a></li>
						<li><a href="generic.html" class="active">Generic</a></li>
						<li><a href="elements.html">Elements</a></li>
					</ul>
				</nav>
			</header>

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<section id="main" class="wrapper">
						<div class="inner">
							<h1 class="major">A Generic Page</h1>
							<span class="image fit"><img src="images/pic04.jpg" alt="" /></span>
							<p>Donec eget ex magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fergiat. Pellentesque in mi eu massa lacinia malesuada et a elit. Donec urna ex, lacinia in purus ac, pretium pulvinar mauris. Curabitur sapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique.</p>
							<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fersapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique lorem ipsum dolor.</p>
						</div>
					</section>

			</div>

		<!-- Footer -->
			<footer id="footer" class="wrapper alt">
				<div class="inner">
					<ul class="menu">
						<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/browser.min.js"></script>
			<script src="assets/js/breakpoints.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>

Code/Server/Django_Web_REST_Server/templates/iptables_index.html
<!DOCTYPE HTML>
<!--
	Hyperspace by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    {% load static %}
    <title>Login IoT Config</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href = {% static 'assets/css/main.css' %} />
    <noscript>
        <link rel= "stylesheet" href = {% static 'assets/css/noscript.css' %} />
    </noscript>
</head>
<body class="is-preload">

<section id="sidebar">
    <div class="inner">
        <nav>
            <ul>
                <li>User: {{ user.get_username }}</li>
                <li><a href="{% url 'config:home_store_view' %}?next={{ request.path }}">Home</a></li>
                <li><a href="{% url 'config:logout' %}?next={{ request.path }}">Logout</a></li>
            </ul>
        </nav>
    </div>
</section>

<!-- Wrapper -->
<div id="wrapper">
    <!-- Intro -->
    <section id="intro" class="wrapper style1 fullscreen fade-up">
        <div class="inner">
            {% load render_table from django_tables2 %}
            {% block content %}
                <h1>Your iptables configuration:</h1>
                {% render_table table %}
                <form method="get" action={% url 'config:new_iptables_config' %}>
                    <input type="submit" value="Create new configuration">
                </form>

                </div>
                </section>


                <section id="two" class="wrapper style1-alt fade-up">
                    <div class="inner">
                        <h2>Delete a Configuration</h2>
                        <p>Delete a configuration by typing its id into the textfield.</p>
                        <div class="split style1">
                            <section>
                                <form method="POST"
                                      action={% url 'config:delete_iptables_config'%} class="post-form">{% csrf_token %}
                                    <div class="fields">
                                        {{ form.as_p }}
                                    </div>
                                    <button type="submit" class="save btn btn-default">Delete</button>
                                </form>
                            </section>

                        </div>
                    </div>
                </section>


                <section id="two" class="wrapper style1 fade-up">
                    <div class="inner">
                        <h2>Uninstall</h2>
                        <p>If you want to uninstall iptables click the button</p>
                        <div class="split style1">
                            <section>
                                <form method="POST"
                                    action={% url 'config:uninstall' id %} class="post-form">{% csrf_token %}
                                    <button type="submit" class="save btn btn-default">Uninstall</button>
                                </form>
                            </section>

                        </div>
                    </div>
                </section>

            {% endblock %}
</div>
</body>
<!-- Footer -->
<footer id="footer" class="wrapper style1-alt">
    <div class="inner">
        <ul class="menu">
            <li>&copy; Leon Lukas. All rights reserved.</li>
        </ul>
    </div>
</footer>

<!-- Scripts -->
{% load static %}
<script src={% static 'assets/js/jquery.min.js' %}></script>
<script src={% static 'assets/js/jquery.scrollex.min.js' %}></script>
<script src={% static 'assets/js/jquery.scrolly.min.js' %}></script>
<script src={% static 'assets/js/browser.min.js' %}></script>
<script src={% static 'assets/js/breakpoints.min.js' %}></script>
<script src={% static 'assets/js/util.js' %}></script>
<script src={% static 'assets/js/main.js' %}></script>

</body>
</html>

Code/Server/Django_Web_REST_Server/templates/new_config_from.html
<!DOCTYPE HTML>
<!--
	Hyperspace by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    {% load static %}
    <title>Login IoT Config</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href = {% static 'assets/css/main.css' %} />
    <noscript>
        <link rel= "stylesheet" href = {% static 'assets/css/noscript.css' %} />
    </noscript>
</head>
<body class="is-preload">

<section id="sidebar">
    <div class="inner">
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    <li><a href="{% url 'config:logout' %}?next={{ request.path }}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'config:login' %}?next={{ request.path }}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</section>

<!-- Wrapper -->
<div id="wrapper">
    <!-- Intro -->
    <section id="intro" class="wrapper style1 fullscreen fade-up">
        <div class="inner">
            {% load render_table from django_tables2 %}
            {% block content %}
                <h2>New Config</h2>
                <form method="POST" class="post-form">{% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save btn btn-default">Save</button>
                </form>
                 <form method="get" action={% url 'config:app_view' 1 %}>
                    <input type="submit" value="back">
                </form>
            {% endblock %}

        </div>
    </section>



    <!-- Footer -->
    <footer id="footer" class="wrapper style1-alt">
        <div class="inner">
            <ul class="menu">
                <li>&copy; Leon Lukas. All rights reserved.</li>
            </ul>
        </div>
    </footer>

    <!-- Scripts -->
    {% load static %}
    <script src={% static 'assets/js/jquery.min.js' %}></script>
    <script src={% static 'assets/js/jquery.scrollex.min.js' %}></script>
    <script src={% static 'assets/js/jquery.scrolly.min.js' %}></script>
    <script src={% static 'assets/js/browser.min.js' %}></script>
    <script src={% static 'assets/js/breakpoints.min.js' %}></script>
    <script src={% static 'assets/js/util.js' %}></script>
    <script src={% static 'assets/js/main.js' %}></script>

</body>
</html>